global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['localhost:8088']  # Met à jour l'adresse si nécessaire
        labels:
          job: 'jenkins'
